### PR TITLE
Add withLibraries to run custom functions

### PR DESCRIPTION
**Pull request by youngminz**
While looking at the project, I've found that there was no way to add a custom function when using `ScriptHost`. I've added `withLibrary` function that can easily add the new custom functions.

Thanks for open source this project, and thanks for taking a look at my PR!

### CODE REVIEW

**Comment by snazy** [comment]
Hi @youngminz !

Thanks a lot for your contribution! This is really useful stuff!

I've just approved the CI run and realized that the build's a bit unhappy about the (C) year change. Can you revert that last commit? I've opened #88 to address the spotless issue in the build.

**Comment by youngminz** [comment]
@snazy Sure! I will revert the last commit.

**Comment by youngminz** [comment]
Yay! All test passed!

**Comment by snazy** [comment]
Thanks a lot for your contribution!

**Comment by snazy** [comment]
@youngminz just released a new version with your change - should appear soon in public maven repos.

**Comment by youngminz** [comment]
@snazy I verified that the withLibraries function works fine in the new version. Thank you so much for the quick release!

**Pull request merged**
